### ISSUE TITLE
方便提供悟空CRM的依赖项目Dockerfile吗?

### ISSUE THREAD

**Issue by 11006281** [chaiyd/docker#1]
As title.....

感谢大神了

**Comment by chaiyd** [comment]
悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像

**Comment by 11006281** [comment]
> 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像

如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整

**Comment by chaiyd** [comment]
> > 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像
> 
> 如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整

可以的，不过需要等几天，时间上我也没有办法保障，我只能说我尽快，这个需要处理的依赖项太多了

**Comment by 11006281** [comment]
> > > 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像
> > 
> > 
> > 如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整
> 
> 可以的，不过需要等几天，时间上我也没有办法保障，我只能说我尽快，这个需要处理的依赖项太多了

没关系，您有空有闲没事做的时候写就行，我只是很想研究，想知道原理，不然我暴力一点也可以直接拉一个 linux 全部包在同一个容器 哈哈 不过这样好像就失去打包的好处了

**Comment by chaiyd** [comment]
> > > > 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像
> > > 
> > > 
> > > 如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整
> > 
> > 
> > 可以的，不过需要等几天，时间上我也没有办法保障，我只能说我尽快，这个需要处理的依赖项太多了
> 
> 没关系，您有空有闲没事做的时候写就行，我只是很想研究，想知道原理，不然我暴力一点也可以直接拉一个 linux 全部包在同一个容器 哈哈 不过这样好像就失去打包的好处了

已经添加了，但是我没有测试，需要你测试看看有没有什么问题。docker-compose 我也已经修改过了。 你可以直接拉取chaiyd/wkcrm:11.3.2  这个镜像。也可以自己docker build

**Comment by 11006281** [comment]
> > > > > 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像
> > > > 
> > > > 
> > > > 如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整
> > > 
> > > 
> > > 可以的，不过需要等几天，时间上我也没有办法保障，我只能说我尽快，这个需要处理的依赖项太多了
> > 
> > 
> > 没关系，您有空有闲没事做的时候写就行，我只是很想研究，想知道原理，不然我暴力一点也可以直接拉一个 linux 全部包在同一个容器 哈哈 不过这样好像就失去打包的好处了
> 
> 已经添加了，但是我没有测试，需要你测试看看有没有什么问题。docker-compose 我也已经修改过了。 你可以直接拉取chaiyd/wkcrm:11.3.2 这个镜像。也可以自己docker build

目前打包运行成功了，但还没有整合测试，另外发现一个小bug，wkcrm.sh 开头应该要为 #!/bin/bash ，否则会出现语法错误，感谢您分享~我继续研究一下如何整合起来运行

**Comment by chaiyd** [comment]
> > > > > > 悟空CRM的dockerfile 你需要的话，等过几天我写一个吧，现在我是直接拉的官方的镜像
> > > > > 
> > > > > 
> > > > > 如果可以的话就太好了....我研究了很久实在不知道该怎么自己打包，虽然可以利用一些工具去查看镜像的原始dockerfile，但还是不完整
> > > > 
> > > > 
> > > > 可以的，不过需要等几天，时间上我也没有办法保障，我只能说我尽快，这个需要处理的依赖项太多了
> > > 
> > > 
> > > 没关系，您有空有闲没事做的时候写就行，我只是很想研究，想知道原理，不然我暴力一点也可以直接拉一个 linux 全部包在同一个容器 哈哈 不过这样好像就失去打包的好处了
> > 
> > 
> > 已经添加了，但是我没有测试，需要你测试看看有没有什么问题。docker-compose 我也已经修改过了。 你可以直接拉取chaiyd/wkcrm:11.3.2 这个镜像。也可以自己docker build
> 
> 目前打包运行成功了，但还没有整合测试，另外发现一个小bug，wkcrm.sh 开头应该要为 #!/bin/bash ，否则会出现语法错误，感谢您分享~我继续研究一下如何整合起来运行

ok，我已经修改了，你可以使用docker-compose，我已经修改过了，应该是可以直接运行的。
